<?php

use Illuminate\Database\Seeder;

class ConsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $cons=[
			['cons'=>"East batteries! On-off switch too easy to maneuver.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Eats...no, GULPS batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Awkward ergonomics, no optical viewfinder, short battery life, slow, gets hot",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery eating beast/slow to recharge",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"power runs out before pictures do",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Slow, high battery consumption rate.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"image size and quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Memory too small, slow charge between shots.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Case design, included software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No Optical Viewfinder, No Carry Case",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"poor image quality, flash that thinks it's &amp;quot;intelligent,&amp;quot; awkward to handle.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"I haven't discovered any!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"That little on/off switch sucks",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Low light photography, blinding flash",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"a little expensive, but it's worth it",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor picture quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Can only hold so many options, the software is lacking in options",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Pics can sometimes be a bit yellowish",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It needs reliable batteries, not cheap ones.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Low battery life, Smart Media not as popular as Compact Flash",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"hard to see view screen, hard to find",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Maybe the price could be 400 dollars.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None that I've found",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"battery life",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Short battery life",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Takes a second or two to actually take the picture after the button is pushed, eats batteries. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Occasionally mis-focuses some subjects in autofocus mode",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"eats batteries, carry several mem cards",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Viewing screen in bright light.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No viewfinder, no lens cap",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"no support CompactFlash, a little slow, poor batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"battery consumption, warm up time.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Sucks batteries like there's no tomorrow",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It uses a lot of batteries.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"falls apart way too easy",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Needs batteries all the time",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Software instructions difficult to understand and implement",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"image quality is less than perfect",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery hog",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Memory size (needs upgrade)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"it only works sometimes, poor picture quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"???",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Eats batteries. Not enough space for quality pictures.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Low battery life with standard batteries.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Green light in viewfinder, eats AA batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"As listed above",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Hard on batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"no Zoom!! price, heavy/bulky, ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor quality pictures, High power consumption, Low memory size",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery life, green light in viewfinder annoying",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No USB connection",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Missing zoom, few zippy features",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Carbon unit accessory sometimes takes bad pictures with it; 640x480 res has its limits",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery drain, com port only, NO ZOOM, ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery Killer, A little bulky",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Instructions should be more user friendly. Manual assumes computer skills that a beginner may not have",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Doesn't  have a swivel body. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Problems with software, lack of instructions, lack of troubleshooting help, easy to delete pics",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"uses batteries very quick",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"when the computer is down, it won't work",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"uses batteries fast",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"High battery drain, Distracting flash indicator",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Manual is on Software and not as separate item.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Only loads into computer half the time with associated software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No zoom!!!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"battery eater",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Options are $$$$$$$",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"performance",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Eats batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Harder to use in low light",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Durabilty, lack of zoom",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"battery hog",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"bad indoor pics.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"no zoom",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Continues to break down",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None yet",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Malfunctioned twice, goes quickly through batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"battery cost a little high",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Good, but not serious quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery eater, have to connect to computer every time you download pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Eats up batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Flash not too 'smart', software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"you have to buy a battery charger and rechargeables",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery life stinks, flash overexposes closeups, no zoom",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Devours batteries, white out on closeups with flash",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"short battery life",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Lack of Windows2000 Drivers, No Zoom",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"LCD hard to see in the sun, LCD freezes",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Eats batteries, plan on shelling out more money, Not very high res",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Very Poor customer service.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"The camera I have can only be connected to your computer via a serial port, and as I have a serial mouse and a serial modem, I have no spare ports while online, forcing me to disconnect to upload new pictures. :-( [Update: I now have a PS/2 mouse and can p",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Potentially weak LCD screen",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Slightly dated technology",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No Auto-Focus, Weak Flash",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Rechargeable batteries are a must!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"low quality pictures, drains batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery life when using LCD, no zoom",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"printing photos is hard for me",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"eats batteries quickly,  viewfinder too far from lens, sporadic LCD window",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"As with all digital cam's...eats batteries.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Batteries can go fast if you dont get good ones",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Has flaws which are made worse by bad service policy.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"battery life (just buy lithium or rechargeable and it's GREAT); storage capacity (upgradeable)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"does not have zoom",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery Life",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Serial cable only (No USB capabilities), Slow Uploading time.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"An absolute battery hog",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"cam broke/wont upload battery drainer NOT MAC/usb supported",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Eats batteries like crazy; frustrating problems, no USB",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"uses a lot of batteries, and doesn't take good close ups",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"ITS YOUR FIRST DIGITAL CAMERA TO PLAY WITH!!!! :)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Camera is slow, batteries rattle and delete settings, uses batteries up VERY fast.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"8 months later I still have not received the $40. rebate that I was promised",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"almost non-existent tech support",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It's easy to use even for children.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"The camera kept breaking.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Holding the camera steady for 5 seconds after taking picture, Not XP compatible",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Too little space to answer",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"quality and customer service",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It ain't a $1600 Olympus!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Tech support virtually non-existent; ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Pictures only good for email.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"You only get what you pay for.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"VERY low resolution.  Will not take good enough pics for eBay or email",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Weak flash, no memory expansion slot, customer service",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none, just be aware of what it was made for",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No LCD.  Menus are less than clear.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"flash not great",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No expandable memory. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No memory upgrade or color LCD display.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"If you want to spend more, you can get more resolution and memory.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Flaky hardware, *extremely* sensitive to motion during picture taking, mediocre picture quality.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Photos are mediocre.  Lighting can effect web camera adversely",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"7-second wait time in between pictures.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Flash-Range",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No-LCD, so-so image quality, batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Flash kills batteries, bad with low light, no macro mode.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"no zoom",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Picture quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No LCD, No Video Out, Batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Flash distance, poor results in room light",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery life, flimsy USB cover",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Short battery life, so-so indoor pic quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"turns off after about 15-30 seconds w/o use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"battery life, flash too strong with artificial lights, long time between shots.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"weak flash, video-conferencing feature is kinda crummy too",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"not great resolution, IT BROKE!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery life is very limited",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery use &amp;amp; Mac compatability",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"batteries go dead after a short time",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery Consumption",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"uses a lot of batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"no optical zoom, slightly bulky, odd battery gauge.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"shutter delay, slow flash charge, low battery life",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Does not meet advertised specifications.&amp;#13;&amp;#10;No support.&amp;#13;&amp;#10;",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Tiny button for people with large hands",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"eats batteries, difficulty downloading",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not easy to operate, eats batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"poor to no customer service, not for MAC despite claims",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery use/Design",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"short battery life, annoying glare, need to restart Mac every time you want to transfer pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Little memory, excessive battery usage",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery drainer",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Eats batteries, have to buy optional power supply",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Somewhat flimsy, no flash memory, media more difficult to acquire.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"eats batteries!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Battery hog, poor LCD screen",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Miserable battery life, poor battery cover lock integrity",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Latency between pics, size, construction flaws",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No Continuous Zoom, Lens doesn't swivel, Long warm-up time, Photowise 2.1.2 lacks features of earlier versions, LCD has slow scan rate",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"USB connection to my Mac doesn't work most of the time, Usability design",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Needs computer to retain some settings; may not be Y2K compatible",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"can't think of any except eats batteries but I think all digital cameras do that. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor Quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"bulky for today's standards",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"doesn't always work",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"all else",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"camera breaks, Agfa does nothing except tell lies",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"A little big for small hands.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Bad quality in low light, bulky case, slow LCD",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Everything else",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"everything",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It was free...",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor image quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"picture quality, no USB interface",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Low resolution, quirky file transfer",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"grainy images, distortion, poor quality images",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"extremely poor images",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"low quality pictures, eats up batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"bad bad bad pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"I kind of feel bad for the person that bought it.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"all-should be taken off market",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Lack of quality customer service.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"extremely poor image quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"You get what you paid for.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Horrible image quality, pathetic battery life, no focus, the list goes on...",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"poor clarity",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"adapter and battery usage",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"just about everything about it",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"feels junky",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Substandard image quality, confusing software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"dont like it ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"everything about it!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"poor image resolution; high battery usage; not upgradable",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Limited capabilities, shaky software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Just plain doesn't work.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Where shall I begin?",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"waste of money",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Quality of Pictures, and the Company's lack of service to this customer",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"ahhh....it died!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"EVERYTHING",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"stupid stupid stupid, don't buy it, i beg you!!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Doesn't produce decent photos without incredible effort",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"very expensive for a piece of junk",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Low quality, not for taking important pictures.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Still not a good deal",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Bad quality, doesn't work sometimes.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Needs $50 power adapter not included. Poor resolution of picture.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"bad quality, poorly made",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"picture quality, battery use, no view",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Everything from its hard instillation, too is unacceptable performance",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"image quality, battery life, usability",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"read all opinions for the cons",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"quit working, poor quality pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Pixellation in photos, some software troubles, hard on batteries",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"agfa lies about product specs",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"EVERYTHING",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"EVERYTHING",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Horrible quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"bad picture quality/ battery drainage issue",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"fuzzy pics, connection problems, list goes on ...",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Picture quality is useless",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"not the best quality  sucks battery power",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"TAKES BAD PICTURES",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"SUCKS,SUCKS, SUCKS!!!!!!!!!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Low quality service, pictures, software, and warranty",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"problems with software and batteries, low resolution",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Picture quality is utterly awful",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"everything",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"the fact that it exists",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"poor quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"buy a battery for every photo you plan on taking, don't plan on the photos being very good",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Very low end",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"battery life, ease of use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Absolutely everything. Terrible picture, battery life",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Short battery life, awful image quality, poor construction, terrible software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It is a battery eating machine!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Pictures are very grainy and seem out of focus",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Smile is very low-end, not for the serious digital photo lover.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Hard to use, poor quality pictures, battery life.. ha ha.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"or you can say there's nothing good about it.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"short battery life, poor resolution, no&amp;#13;&amp;#10;customer service, badly constructed",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Lens distorts, resolution is low, needs lots of light, gobbles AAs, looks toylike",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Serial port, only 2mb memory ( 16 pics is not enough ), ugly pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"poor image quality, no display",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Resolution ... 1.2 mp  is the base for most graphic work... but ..just enough",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"no flash, annoying beep when buttons pressed, shutter button in an uncomfortable spot",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor low light/indoor picture quality.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor low light performance, drains batteries, no flash.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Cheap plastic hardware&amp;#13;&amp;#10;No flash",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It likes a lot of light, but for the money I have no complaints.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Needs a lot of light.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Software does not allow conversion from bitmap to jpeg formatting. Fragile. Low light problems",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Takes getting used to because of small size., , Some trouble installing due to missing files.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No flash, bad as a webcam, no customer support.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Short battery life, low end picture quality, no flash, beeping noise",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"design flaws and missing features, marginal image quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Why would a spy camera BEEP when pictures are taken?",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"low image quality, can be flimsy ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Image quality is poor without good lighting, may break if dropped, ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Irritating beep when camera takes a picture, no flash on camera.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No flash, marginal lens.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"OK Image Quality, No Flash, Battery Drainer, Few Features, Spoils-the-Fun Beep when Taking Pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No flash, Not for low light situations",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"no flash &amp; you lose all your pix if the battery goez dead . ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"cheap plastic parts&amp;#13;&amp;#10;poor low-light performance&amp;#13;&amp;#10;marginal image quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"drains batteries, bad photo quality, software only works with Windows 98 and above",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor picture quality and no flash.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor picture quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not the best digital camera available.  No flash.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"marginal image quality; limited storage; inadequate product support",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Image quality is so-so. No flash.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"poor quality photos, battery problems, no flash, endless cons",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"clip on it does not stay hooked to what ever you clip it on",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Bad pictures, flimsy, not worth the money.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Won't take pictures in low light.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"quirky software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"You need lots and lots of light to use this one.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Noisy, costly, grainy plain paper printouts, ease of changing cartridges",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Slow and noisy, uses a lot of ink.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Probably not for photos; loud.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Are there any?",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"need to clean print head occasionally",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"noisy, big",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"takes a few moments to change ink cartridges",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Loud, cartridges have to be cleaned for real quality color",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"can't print, lousy support, bad communications, never again",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Hard to find replacement cartridges",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"As always, expensive inks.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Expensive running costs, noisy, large, problems with non-Epson consumables.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"somewhat noisy",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Hmmm..... No cons come to mind !",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"cartridges are still expensive (shop around)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Price, constant maintenance",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Ink cartridges are pricey",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Ink cartridge monitor system leaves something to be desired.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not a one",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"slow for photos, expensive ink costs, loud",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"medium quality on regular paper, ink hog",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Epson does not support: has lines in output",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"haven't found any",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Minor nozzle clogging issue in some situations",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"blurred picture, price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"if you use paper less that 24lb, the printer will misfeed the paper",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"price, cartridges are expensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Macintosh LocalTalk needs an optional interface card.  Some information only in electronic version of the manual.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Loud",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Unacceptable black text.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Hard to find ink",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"A bit loud and shakes when printing",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Printer may shake desktop.  Black text rendition poor.  See opinion for work-around.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Pretty loud",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Very noisy!  Design is bigger and clunkier!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"loud, takes a long time to warm up/print a page",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Loud, high priced, and not that great on black text.&amp;#13;&amp;#10;",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Noisy, does not allow for stiff copy.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"lack of a LCD",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"a little pricey",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"warmup takes longer than the &amp;quot;ready&amp;quot; light indicates",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"That paper tray!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Price is high for most consumers, size",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"nod LCD screen, drivers can conflict.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Lack of Flash and Focusing Ability",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Pictures not the best.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Pictures not the best.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Your best photo's will be bad.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Your best photo's will be bad.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor quality photo's",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Horrible picture quality; no flash. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor quality, no flash, outdoor pictures only.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"You get what you pay for",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Low pic quality. not hold many pic's on High Resoultion (20) Low resolution (80)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Drivers not XP compatible&amp;#13;&amp;#10;Product Support Minimal&amp;#13;&amp;#10;Product Doesn't Work",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Eats batteries up so fast that they must be removed after use!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Where should I begin? No flash, no removable memory",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Picture quality is very poor. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Low quality pictures, no flash",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"does not work... get what ya paid for",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"very vague instructions, pictures arent very high quality, not much memory",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"You get what you pay for",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"poor quality photos, cheap, no lcd screen",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Your best photo's will be bad.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not cheap enough, found better stuff in Cracker Jack boxes",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No removable memory, no flash",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor quality pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"no flash, hard to understand directions, cheap construction",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Picture quality isn't that good, cheap design and construction, no flash makes lighting necessary",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Mine is under the Vivitar brand name ,but the same camera !",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor optics, puny internal memory, ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"USB problems, Problems powering up, didn't operate properly",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not worth the money",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Little built in memory, short range",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"about .5mb of internal memory, battery &amp; CF doors are hard to open/close",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"grainy LCD preview; poor picture quality; flash broken",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Defective and the quality?",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"a little difficult to fold down",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"A little bit expensive for those new mothers.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>" Can't push it while lying on the couch.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Expensive, can tip over",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Hard to travel with.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"The price, and its bulky",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Kind-of Bulky in Malls",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"baby pushing up can cause it to topple backwards",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None found yet",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Price. Size. Does not fold up easily.  ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Expensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Almost too big for everyday use.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Its hard to manipulate if you take it in large crowds",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Doesn't fold, unless you disassemble it, and is still extremely bulky. Only one seat position.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"I don't know of any",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Bulky when folded, doesn't lock in the folded position",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"expensive, lacking all the cutesy gadgets others have",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"That it can sometimes get a little out of control",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Cost, takes some adjustment getting used to pushing while jogging.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Stroller doesn't turn easily, rear wheel alignment problems cause it to drift",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"doesn't fold up the best",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Too large",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Cheaply made, uncomfortable, no head support or cushioning. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"expensive, brake hard to set",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Hard to store and travel with, not very comfortable for toddlers",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"not made for people over 6'2&amp;quot;",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No more excuses for not running",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"May not fit into small car",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Expensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not good on rough terrain",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Spendy, Balance and Design Issues",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"A little hard to get up curbs.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"wheels are too big",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Kind of bulky",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Like a bike, tires can go flat easily.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Baby can't recline, access to basket is small, brakes don't engage on the first try",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"lacks parking brake, sun shield is too small, somewhat awkward to fold",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"somewhat bulky in size ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"basket on bottom is small",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Bulky to transport",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No adjustable recline position",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"You can't use it to go shopping at the mall.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"3 wheels are better than 4",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"higher price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No stationary brakes.  ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None, this is the 'perfect' sports stroller",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Hard to get., Pricey",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Takes a little while to get the hang of putting together",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"A little bulky to get into a small car",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Balance problem and it's hard to put away",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Price Can Be a Drawback",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not reclining seat",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"more pricey than other joggers",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"seat doesn't recline - minor issue.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"One sitting position",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Folding it can take some getting used to",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"pricey, small baskets",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"just alittle pricey but worth it!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"expensive and not for infants",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"too wide to use indoors, expensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"breaks easily with a little wear and tare.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"somewhat heavy",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"took awhile to get used to",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Expensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"less than eight wheels",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Break down is a little awkward.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It's a bit pricey, but well worth every penny",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"price, wheels ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"you need a large trunk, minivan, or truck",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It has tipped over on occasion, only once with baby inside!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Straps caused minor discomfort, but otherwise no complaints!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"The turning is not that easy",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Needs a parking break; strap between the legs is too long (can be remedied); retracted canopy brushes against an older childs head.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor canopy design.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Canopy, Bottom Mesh Basket",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"See Review for product comparisons",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"NOT for babies, huge, expensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Won't replace the need for a small stroller.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"A little steep in price(but worth it)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"the attachment bar then makes it hard to fit into some vehicles ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Folding and unfolding is akward and there is no cup holder",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"too minor to mention",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Like most double strollers, it squeaks from time to time",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Squeaky, and quite flimsy after 20 months of heavy use.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"not easy to transport, takes up a lot of room in car, can't use basket with back seat reclined",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"reliability, size",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"small basket, no leg room in rear",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Missing storage, hard to collapse",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Hard to lift in the trunk.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"basket not accessible when used as travel system",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"As of yet, I've not found any!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"High price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"engineering",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Front rider gets kicked and seats do not sit straight up.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Basket inaccessible when back seat is fully reclined",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Gets squeaky and flimsy on the long run",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"doesn't wear well, ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Basket is hard to reach when car seat is attached",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Bulky",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Baby Trend difficult to reach by phone",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"small storage area, no handle height adjustment",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Like pushing an Explorer through the mall. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Yeah, I'd like to see YOU keep MY toddler in the standing position!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Too heavy, somewhat flimsy",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Storage basket can't hold very much, no cup holders.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"hard to push and turn",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"When using infant carrier, older child cannot sit; somewhat heavy; manuvering in stores takes practice!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Fairly large and heavy, small basket.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"bulky,  storage difficult to access",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"basket hard to reach",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"May not allow enough room for taller child in weight range",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Too big, heavy and hard to manuver",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"long distance catapulting of occupant due to lack of brakes",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"bulky for storage",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"heavy",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Outgrow fast",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Hard to maneuver",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Folding up a BIG hassle, heavy, feels cheap.  ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Small storage basket",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"strong and reliable",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not realistic.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Too big and cumbersome",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"flimsiness",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"front pops out",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"basket location",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Front seat doesn't recline much",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"not designed for young children, expensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"a little pricey",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"very awkward to collapse",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"lots of repair problems, hard to steer, heavy",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"harder to fold",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"seat positions",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"infant part needs more padding",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"My children don't like to stand when the front seat is reclined",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"not as small as normal one child strollers, not a great harness system for older child",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"can't sit on back while front is reclined fully",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"can't think of any",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Storage access!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Infant seat attachment makes stroller bulky!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Maneuverability",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"not suitable for 2 pretoddlers",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Too heavy, hard to fold and unfold, safety concerns for standing child.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Poor design",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"toddler not restrained enough",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not enough room on jumpseat, not a good seatbelt, very heavy",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Heavy,  Basket inaccessible, Probably was not the best choice for our needs",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"not for wanderers",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"not for 2 small children",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"bulky and hard to maneuver when closed",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"seat only has 2 reclining positions",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Can be pushed by child sitting in back",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"HEAVY",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"worst stroller I have ever used",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Toddler cannot always sit",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"child in the front seat will grow out of it fast.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"hard to push and turn",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Size",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"child can fall off when standing",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"heavy - awkward to fold up and basket hard to access.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Basket is not easy to get too! Needs a cup and bag holder for parents.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Heavy,and hard to turn.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Software not XP compatible, scanner is slow and scan quality not up to par",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Too bad it doesn't do color printing.  Slow on the hi-res color scanning otherwise great.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Needs linux drivers.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none so far",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Horrible customer service",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Slow First Copy, Not Color (inkjet), Small Document Bed",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Slow scanner.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Edges of copies may bend on output tray",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Drum unit gave out after 13 months of light home use.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Driver could be better, sometimes has errors",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No network port. No color. No cable in box",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"only 2mb (enough for normal duty)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Needs more documentation on CD",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Short drum life, obtrusive software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"USB, Power Consumption",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"USB setup is difficult.  Very still cardstock may be a problem.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Quite large",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Crappy software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None that i can think of!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not a Postscript printer",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Memory is not upgrade able.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Could have better quality.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Limited expansion possibilities",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Limited On Board Memory, Slightly Hard To Find In Stores and On The Web",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"USB installation could be more seamless",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No automatic envelope feeder, the paper tray fits both letter and legal which makes it stick out beyond the printer body in the rear of the machine.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Only 2MB memory, nonexpandable or networkable.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"manual feeding a touch tricky, beige",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Somewhat large",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"print quality not a crisp black color",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"inability to increase RAM",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"the name isn't HP",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"NONE",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"buggy USB driver",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None yet",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Bare-bones Mac driver; PostScript not available",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Paper tray sticks out back",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Won't work well with older computers, support is difficult",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"The toner cartridge is difficult to find.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Fairly large, 2MB memory may not be enough for some",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Can't be networked.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"doesn't work well in network environments",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not good for printing envelopes",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"High-Res graphics are a little fuzzy.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None yet.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Square design, 4MB memory not enough for some image printing, supplied drivers not excellent",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Susceptible to jamming",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It glitches on occasion, but doesn't everything.  This does it less, though.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"print shade",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Annoying Quick Setup Dialog Box - Doesn't work well with Win XP",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None so far.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Paper Handling could be better.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Just prints b&amp;w, toners are costly",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Feeding heavy stock from paper tray, incorrect instructions for printing a test page.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Clearing paper jams can be tricky, requires significant component replacement periodically.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No print density control: prints too light with some fonts.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Can only load one piece at a time in manual loader",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Unreliable USB interface.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Drum Unit Assembly",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Setup - possible hitch.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Relatively_long warm-up time. It_needs more memory for graphics. Replacing_the drum unit will hurt (financially).... ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Can't print a lot of graphics; customer service isn't great.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Buggy software drivers.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Tray can be tricky to slide out",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"I tis not a color Printer (Joking)Can't think of any",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Noisy when operating",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Windows XP users may have to download additional software to use this product",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"The drum kit burns light weight glossy paper, too high of heat.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Low memory means restrictions on printing graphics",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"The tray should be bigger to hold more paper.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Approx 70 pct of time it will not print an address on an envelope. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Not for graphic or color prints jobs.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Nothing really",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"You must download drivers for windows xp",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Trouble with graphics.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"toner cartridge problems - gray background after 500-750 pages new machine",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"smell of cartridge ink; inconsistent manual feed",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"It continually jams when printing envelopes. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Too cheap to keep",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"As loud as my paper shredder, Dimmed the lights in my room, Slow to print",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No USB or Parallel cable included.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"none so far",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"many jams, awkward to clear; streaking; sucky documentation",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Some paper jams, computer freeze-ups, software takes a while to figure out.  Somewhat slow.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Annoying paper jams.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"No phone handset",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Multiple Sending at the same time has problems",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Zero customer service",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"The paper port does not have writer capabilities.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"SLOW and mine may have defective print heads",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"Address book",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['cons'=>"None so far.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
		];

		\App\Cons::insert($cons);
    }
}
