<?php

use Illuminate\Database\Seeder;

class ProsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $pros=[
			['pros'=>"Easy to use, economical!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Digital is where it's at...down with developing film!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good image quality, 3x optical zoom, macro mode, inexpensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Awesome features/easy to use/fun/versatile/low price/Cust SVS 2nd 2 none!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"intuitive, user friendly",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Simple, Flexable, Reliable",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"battery life, download speed",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Agfa quality in a small box, great for table top and tests",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Image quality, price, video link",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"No Extras to Buy, Very Flexible, High Quality Images, Good Software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"simplicity",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Comes with software, good price, excellent pictures.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Clear pics",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price, Over all Performance, Zoom Feature",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"clear, srisp picture, durable camera, good desing, nice features",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive compared to some",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Great picture quality, swivel lens, many options",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Very simple controls and a wide range of features",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Great camera, easy to use, good looking, high quality images.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Megapixel quality, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"durable, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Sharp, crisp, pictures.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Ease of use, quality pictures.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"pic quality, smart media,price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"megapixel quality, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, takes GREAT pictures, full of features.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Saturated, sharp images at all resolutions, twist-style body",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"very clear photos",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Nickle Hydride batteries,  ease of use, excellent color rendition",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Picture quality, Twist body",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"perfect shots, long-focus, easy to use, a lot of features, good software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, stylish, good picture quality, good price, good company.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good quality pictures for a low price, great first camera",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"This camera is a nice easy to use camera.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Takes great pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive and clear pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Camera is very easy to learn and use.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"extra film, led for image viewing, software is easy to use, sleek design",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, great pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Ease of use; instant review; inexpensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cheap",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive, good quality, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Acceptable Quality Pictures. Decent amount of options.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Low price, easy to use. Quality pictures.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Low price, 4 levels of resolution, EZ to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"None",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, fabulous picture quality, lots of features",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"sturdy, easy to use, ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Strong, Well Built body",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Attractive, easy to use, great value",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"No internal memory (uses cards), lightweight, compact, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Swell buy for the price, ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive, versatile, fun, sturdy, and cool.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Ease of use, TV connection cable, Decent software, interchangeable compact flash cards in many sizes",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price, Quality, Storage capacity",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price, Ease of Use, Great Software package, factory support",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Great Pictures for the Cost.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use - fun at first",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"inexpensive,easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cheaper than buying film",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good value for the money, Simple to learn/use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Quick and easy to use.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Takes great pictures in four resolutions",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Decent resolution",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Fantastic value, great images, solid camera, GREAT company, EXCELLENT customer service (read my 5/20/2000 update)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"sturdy, great price, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good quality inexpensive initially",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cost",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, good quality, great price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy, fast image transfer to PC or printer",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Changing resolution",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"reasonable price This features you would expect from a very expensive camera",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, great outdoor pics.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"simple to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"handy, high quality pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Best camera we  have had",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Great software, easy to use camera",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"User friendly, priced right",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, compact",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, picture galleries, self-adjusting flash",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cute, cheap, anybody could use it",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cheap, cute, sturdy, reliable",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"good for beginners, funky blue design, cheap",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good price for resolution and ease of use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Low cost, easy to use, pretty good pictures, fine for ebay",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"inexpensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price, Style--it's Blue :)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Blue design FUN! Takes good pictures for me, LCD and Optical view finder, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Very easy camera to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use. Great range of settings for the flash, the resolution and the focal length. The camera itself looks pretty darn cool too.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Customer support, value for dollar",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price, Ease of Use, LCD Monitor",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"High Quality Photos, Dependable, Easy to Use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"friendly",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cheap, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price, Great pictures, Smart Media slot",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cost, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"compact, stylish, good quality pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Ease of use, clear &amp;amp; crisp pictures, LCD",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"You get so much for what you pay",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Great camera, great price!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good images, uploadable, easy to use, LCD, everything",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"easy to use, affordable, several nice features",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Wonderful Software Included; Easy-to-Use; Great Picture Quality; Lots of Features; Low Cost",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Gallery, Viewing Lense, High Capacity for storing pictures, Nice Design, High Resolution/Good Quality photos.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Relatively low-cost, decent picture quality and simple to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cool looking. decent pics. like the flash and size options.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use; relatively inexpensive; quality pretty good; wonderful customer service",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"very inexpensive,  good quality pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"GREAT DIGITAL 1ST CAMERA",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Very simple to use, software is pretty self explanatory.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"compact and reasonable pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"zero",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"It's light and low tech.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"The company honored my warranty.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive, Easy to operate",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"NOT ONE",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cost",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"inexpensive, webcam conversion included, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Photos look good on TV",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price. EVERYTHING is included. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"A camera to carry with you at all times.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good for inexpensive snapshots",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"- small, low power consumption, decent outdoor pictures, fast USB connection",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Small, light, simple, pockatable",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cheap.  Complete.  USB interface.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"quality good for price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Tiny camera with lots of big features.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"It is made for video conferencing and still photography with quality  pictures.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Great inexpensive digital camera",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good value, good photos, simple to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Nice picture as a web camera when the lighting is good.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"affordable, high quality pictures, holds a lot of pictures, USB port, pocket-sized, so it's easy to carry around.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Pricing, Image Quality, Dimensions, USB-port, CF-slot, Flash, WebCam",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Small, inexpensive, easy",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to handle, good quality with enough light, webcam too.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good pics,price and easy to use.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Lightweight, small, great webcam",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Image Quality, CF Card Slot, Flash, USB",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Can you find anything better for this price?",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price, ease of use, size.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"CompactFlash, USB, has flash, great outdoor image quality, good for web or beginner",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Flash, Digital, USB, high or low quality, WEB CAM,  ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price/Quality, agfanet prints, size, software bundle, versatility",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive, good pictures in good lighting conditions",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"LCD screen, Clik! drive, navigation nob, easy software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, 1 Megapixel",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"good pic quality &amp;amp; price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"lightweight, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Simplicity, cord bundle, Photo Quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, great picture quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"inexpensive Clik! media, 1.5 MP resolution, 2x digital zoom",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"good image quality, affordable",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Not many.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good $ ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"ease of use, compact size",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Pretty, lightweight, cheap",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"takes good images",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Value",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"photos transfer from camera to software quickly, easy to get started with",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good price, good quality photos.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cheap, easy, good for the amateur photographer",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Ease of use, great quality pictures, cost",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"can be used as a drive, USB compatible, great picture quality, cheaper media.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Excellent Quality, Cheap, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Connectivity options: PCMIA,USB,serial",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good feature control, nice macro feature, good image quality",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"USB, megapixel, mass storage, LCD preview",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive Media, Optical View Finder, Switchable LCD, LCD Cover",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price, Photo quality, weight",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Photowise 1.7; Switchable LCD; LCD cover; optical viewfinder",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use software and camera, came with everything needed to get started right away. ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Easy to use, cheap",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Excellent image quality and expanded storage space",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"nice pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"accessories",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"You can take ALL high-resolution pictures without worrying about space!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"clear pictures, lots of memory space (40MB each clik! disk)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cute little blue camera",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"pretty packaging",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"It was free!",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Ease of use, price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"small, cheap, built in flash",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cheap, functional",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"small, lightweight, can preview images on television",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cheap, cute, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"price, flash, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cheap, E-Z to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"I sold it again on Ebay.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Priced right for a beginner.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"tv-out, webcam capable",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive, Smaller-Than-Pocket-Size",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cheap, tiny.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"user-friendly",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"resolution and price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"small size",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"it has a flash",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive, sleek looking",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"dont like it ",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"light weight; has functions; takes pictures",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Great price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"It is a pretty color and it is very compact",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"takes pics",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Its cheap",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"easy, compact, self timer",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"NON",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"small, light, shiny, blue, cheap",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Looks pretty, has extra functions",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"at least it wasn't take expensive",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cheap, easy to use. Good for web pictures.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"It was free",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cheap, small.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Low cost, light weight, functional",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cheap, light, small",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"size, ease of use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"None, period.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"I'm still looking for one",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cute, easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive, has many features more expensive cameras don't, intuitive interface",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Specs sound good (better than reality)",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Makes a good paperweight",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"NONE",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cheap",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"inexpensive, compact, and looks cool",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"cute design &amp;amp; obvious controls",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cheap, cute.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"priced for value",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"SMALL EASY TO CARRY",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Low price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"nice price, easy interface, many features",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Lightweight, simple to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"low price",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"none",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"None",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"light weight, good construction",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Cheap",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"pretty cheap, small, well labeled",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Absolutely nothing",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Small size, attractive design",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"It was cheap",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Inexpensive and easy to use",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Camera is cheap and functional with a couple of options.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Nada",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Good for scaring small children and a good gag gift.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"None",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Compact, cheap, color, miraculously the software isn't buggy",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Ease to use ...",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"small, light, good resolution, well priced",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"very small uncomplicated and very nice portable tool for graphics students",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Superb Quality Pictures, LOW LOW PRICE, TRUE 1.3megapixel,  super portable",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Small and very light.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"1.3MP digital camera, webcam, extremely small size, simple to use.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Lightweight&amp;#13;&amp;#10;Good value&amp;#13;&amp;#10;Ultra fun",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Surprisingly good pictures and video from this inexpensive tiny camera.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Great quality photos.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Great for email, short videos &amp; conference calling",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Tiny, decent photos, easy to use.",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
			['pros'=>"Tiny Size, Inexpensive, Picture and Video Capture, Over 1 mp, Easy to use Software",'created_at'=>date('Y-m-d H:i:s'),'updated_at'=>date('Y-m-d H:i:s')],
		];

		foreach (array_chunk($pros,1000) as $x) {
			\App\Pros::insert($x);
		}
    }
}
